### PR TITLE
Recognize Unicode ellipsis as punctuation

### LINKED ISSUE #267: Horizontal ellipsis(…) is not considered as valid punctuation causes styling as bold failed
The punctuation characters list in _DelimiterRun does not include Horizontal ellipsis(…) as valid punctuation. This causes the styling as bold failed.

Example: If I try to styling as bold in below format:

"Connecting dot \*\*A\*\*\* to \*\*B\*\*\*…"

It shows

"Connecting dot **A*** to \*\*B\*\*\*…"

If I change the string with three comma:

"Connecting dot \*\*A\*\*\* to \*\*B\*\*\*..."

Then it does the styling correctly:

"Connecting dot **A*** to **B***..."

Here are the screenshots:

Using Horizontal ellipsis(…):
Pic1

Using three comma:
pic2

### PR DESCRIPTION
**Pull request by srawlins**
Fixes #267

### CODE REVIEW

File: lib/src/inline_parser.dart [hunk 1]
```diff
@@ -453,15 +483,15 @@ class _DelimiterRun {
     } else {
       preceding = parser.source.substring(runStart - 1, runStart);
     }
-    precededByPunctuation = punctuation.contains(preceding);
+    precededByPunctuation = punctuation.hasMatch(preceding);
```
Comment (jcollins-g) [inline lib/src/inline_parser.dart]: If this turns out to be too slow consider using a set instead of a regexp for the lookup (since it is a single character, should be OK).

Comment (srawlins) [reply lib/src/inline_parser.dart]: Good call. I'm hoping a once-compiled RegExp produces a fast state machine that is essentially that Set. 😛
