### PR TITLE
fix a crash when parsing alert block syntax

### LINKED ISSUE #577: github alerts parsing doesn't support multiple paragraphs
The new github alerts functionality does render this properly:

```
> [!Note]
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
> incididunt ut labore et dolore magna aliqua.
```

But does not render this correctly (the 2nd paragraph isn't considered part of the alert):

```
> [!Note]
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
> incididunt ut labore et dolore magna aliqua.
>
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
> incididunt ut labore et dolore magna aliqua.
```

### LINKED ISSUE #584: Crash "Bad state: No element" in AlertBlockSyntax.parseChildLines
I ran `test/crash_test.dart` and found 9 markdown files where `package:markdown` crashes:

```
Bad state: No element
#0      List.last (dart:core-patch/growable_array.dart:348:5)
#1      AlertBlockSyntax.parseChildLines (package:markdown/src/block_syntaxes/alert_block_syntax.dart:54:35)
#2      AlertBlockSyntax.parse (package:markdown/src/block_syntaxes/alert_block_syntax.dart:85:24)
#3      BlockParser.parseLines (package:markdown/src/block_parser.dart:178:32)
#4      Document.parseLineList (package:markdown/src/document.dart:87:44)
#5      Document.parse (package:markdown/src/document.dart:83:36)
#6      markdownToHtml (package:markdown/src/html_renderer.dart:40:26)
```

Full log in: https://gist.github.com/jonasfj/9d8dfb702f46e64b78a22f5762ac2f95

This ran a scan of all `.md` files in the latest version of all packages on pub.dev.

--------------

@AlexV525, @devoncarew, could this be related to:
 * https://github.com/dart-lang/markdown/pull/570, or
 * https://github.com/dart-lang/markdown/pull/576

### PR DESCRIPTION
**Pull request by devoncarew**
- fix a crash when parsing alert block syntax (fix #584)
- have alert block syntax support multiple paragraphs (close #577)

@srawlins - this also revs the package version in preparation for publishing (so we can get the fix out for pub.dev).

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

File: lib/src/block_syntaxes/alert_block_syntax.dart [hunk 1]
```diff
@@ -21,8 +21,7 @@ class AlertBlockSyntax extends BlockSyntax {
 
   @override
   bool canParse(BlockParser parser) {
-    return pattern.hasMatch(parser.current.content) &&
-        parser.lines.any((line) => _contentLineRegExp.hasMatch(line.content));
+    return alertPattern.hasMatch(parser.current.content);
```
Comment (devoncarew) [inline lib/src/block_syntaxes/alert_block_syntax.dart:24]: Based on https://github.com/dart-lang/markdown/pull/585#discussion_r1500386589 and https://github.com/dart-lang/markdown/issues/579 I removed the reference here to BlockParser.lines; I suspect it caused quadratic parsing times.

Comment (srawlins) [reply lib/src/block_syntaxes/alert_block_syntax.dart:24]: SGTM

**Review by srawlins — APPROVED** [review]
Great fix for the crash and performance issue. Thanks!
